spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://${auth.host:localhost}:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: storage
          uri: http://${storage.host:localhost}:8081
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: shopping-cart
          uri: http://${shopping-cart.host:localhost}:8082
          predicates:
            - Path=/shopping-cart/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
        - id: payment
          uri: http://${payment.host:localhost}:8083
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
            - AuthenticationFilter
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
authentication-filter:
  host: ${auth.host:localhost}