spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: storage
          uri: http://localhost:8081
          predicates:
            - Path=/storage/**
          filters:
            - StripPrefix=1
server:
  port: 8888
